<?xml version="1.0" ?>

<robot name="ArchiBot_PandT_Camera" xmlns:xacro="https://www.ros.org/wiki/xacro" >


  <xacro:include filename="$(find adescription)/urdf/macros.xacro"/>
  <xacro:include filename="$(find adescription)/urdf/data.xacro"/>
  <xacro:include filename="$(find adescription)/urdf/materials.xacro"/>


  <link name='chassis'>
    <pose>0 0 0.1 0 0 0</pose>

    <inertial>
      <mass value="${chassisMass}"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
<!--        <inertia-->
<!--            ixx="0.5" ixy="0" ixz="0"-->
<!--            iyy="1.0" iyz="0"-->
<!--            izz="0.1"-->
<!--        />-->
    </inertial>

    <collision name='collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
    </collision>

    <visual name='chassis_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
    </visual>


    <collision name='caster_collision'>
      <origin xyz="${-chassisLength/3} 0 ${-casterRadius}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${casterRadius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>

    <visual name='caster_visual'>
      <origin xyz="${-chassisLength/3} 0 ${-casterRadius}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${casterRadius}"/>
      </geometry>
    </visual>
  </link>


  <link name="left_wheel">
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
      <geometry>
        <cylinder radius="${wheelRadius}" length="${wheelWidth}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu1 value="100"/>
            <mu2 value="100"/>
            <slip1>0.01</slip1>
            <slip2>0.01</slip2>
          </ode>
        </friction>
<!--        <contact>-->
<!--          <ode>-->
<!--            <min_depth>0.01</min_depth>-->
<!--&lt;!&ndash;            <kp>1e9</kp>&ndash;&gt;-->
<!--            <soft_cfm>0.2</soft_cfm>-->
<!--            <soft_erp>0.4</soft_erp>-->
<!--            <fdir1>0.000000 1.000000 0.000000</fdir1>-->
<!--          </ode>-->
<!--        </contact>-->
      </surface>
    </collision>
    <visual name="left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
      <geometry>
        <cylinder radius="${wheelRadius}" length="${wheelWidth}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
      <mass value="${wheelMass}"/>
      <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <link name="right_wheel">
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
      <geometry>
        <cylinder radius="${wheelRadius}" length="${wheelWidth}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu1 value="100"/>
            <mu2 value="100"/>
            <slip1>0.01</slip1>
            <slip2>0.01</slip2>
          </ode>
        </friction>
<!--        <contact>-->
<!--          <ode>-->
<!--            <min_depth>0.001</min_depth>-->
<!--&lt;!&ndash;            <kp>1e9</kp>&ndash;&gt;-->
<!--            <soft_cfm>0.2</soft_cfm>-->
<!--            <soft_erp>0.4</soft_erp>-->
<!--            <fdir1>0.000000 1.000000 0.000000</fdir1>-->
<!--          </ode>-->
<!--        </contact>-->
      </surface>
    </collision>
    <visual name="right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
      <geometry>
        <cylinder radius="${wheelRadius}" length="${wheelWidth}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
      <mass value="${wheelMass}"/>
      <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>


  <joint type="continuous" name="left_wheel_hinge">
    <origin xyz="${chassisLength/3} ${chassisWidth/2+wheelWidth/2+0.01} 0" rpy="0 0 0"/>
    <child link="left_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <joint type="continuous" name="right_wheel_hinge">
    <origin xyz="${chassisLength/3} ${-chassisWidth/2-wheelWidth/2-0.01} 0" rpy="0 0 0"/>
    <child link="right_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>40</updateRate>
        <legacyMode>true</legacyMode>
        <leftJoint>left_wheel_hinge</leftJoint>
        <rightJoint>right_wheel_hinge</rightJoint>
        <wheelSeparation>0.4</wheelSeparation>
        <wheelDiameter>0.1</wheelDiameter>
        <torque>20</torque>
        <commandTopic>cmd_vel</commandTopic>
        <odometryTopic>odom</odometryTopic>
        <odometryFrame>odom</odometryFrame>
        <robotBaseFrame>chassis</robotBaseFrame>
        <publishWheelTF>false</publishWheelTF>
        <publishWheelJointState>true</publishWheelJointState>
        <rosDebugLevel>na</rosDebugLevel>
        <wheelAcceleration>0</wheelAcceleration>
        <wheelTorque>5</wheelTorque>
        <odometrySource>world</odometrySource>
        <publishTf>1</publishTf>
    </plugin>
  </gazebo>

  <gazebo reference="left_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="right_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <xacro:include filename="$(find adescription)/urdf/camera_arm.xacro"/>
  <camera_arm/>

  <xacro:include filename="$(find adescription)/urdf/maincamera.xacro"/>
  <maincamera/>

</robot>